services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  web:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432" 
    volumes:
      - db-data:/var/lib/postgresql/data

  node:
    image: node:20-alpine
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  db-data:
